version: "2.29"
services:
  springboot-app:
    container_name: recipe-demo-container
    image: recipe-demo
    ports:
      - 8080:8080
    networks:
      - spring-mysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/recipedb
      - spring.datasource.username=root
      - spring.datasource.password=root
    depends_on:
      - mysqldb
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10

  mysqldb:
    container_name: mysql-container
    image: mysql
    restart: always
    ports:
      - 3307:3306
    networks:
      - spring-mysql-net
    environment:
      MYSQL_DATABASE: recipedb
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
networks:
  spring-mysql-net: